# SPDX-FileCopyrightText: 2022-2023 Shun Sakai and Contributors
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
