# SPDX-FileCopyrightText: 2022 Shun Sakai and other contributors
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
