# SPDX-FileCopyrightText: 2022 Shun Sakai
# SPDX-FileCopyrightText: 2023 zSchoen
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "sysexits"
version = "0.11.0"
edition = "2024"
rust-version = "1.87.0"
description = "The system exit codes as defined by <sysexits.h>"
documentation = "https://docs.rs/sysexits"
repository = "https://github.com/sorairolake/sysexits-rs"
license = "Apache-2.0 OR MIT"
keywords = ["exitcode", "sysexits"]
categories = ["command-line-interface", "no-std", "os"]
include = ["/LICENSES", "/README.md", "/src"]

[[example]]
name = "cat"
required-features = ["std"]

[[example]]
name = "isutf8"
required-features = ["std"]

[dev-dependencies]
clap = { version = "4.5.58", features = ["derive"] }
proptest = "1.10.0"
test-strategy = "0.4.5"

[features]
default = ["std"]
std = []

[lints.clippy]
cargo = { level = "warn", priority = -1 }
multiple_crate_versions = "allow"
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

[lints.rust]
missing_debug_implementations = "deny"
rust_2018_idioms = { level = "warn", priority = -1 }
unsafe_code = "forbid"
