# SPDX-FileCopyrightText: 2022 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: CI

on:
  pull_request:
  push:
    branches:
      - "develop"
      - "master"
  schedule:
    - cron: "0 0 * * 0"

jobs:
  check:
    name: Check
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os-alias:
          - ubuntu
          - macos
          - windows
        toolchain-alias:
          - msrv
          - stable
          - nightly
        include:
          - os-alias: ubuntu
            os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os-alias: macos
            os: macos-14
            target: aarch64-apple-darwin
          - os-alias: windows
            os: windows-2022
            target: x86_64-pc-windows-msvc
          - toolchain-alias: msrv
            toolchain: 1.62.0
          - toolchain-alias: stable
            toolchain: stable
          - toolchain-alias: nightly
            toolchain: nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.7.7
        with:
          key: ${{ matrix.target }}
      - name: Check a package
        run: cargo check --target ${{ matrix.target }}
      - name: Check a package (no default features)
        run: cargo check --target ${{ matrix.target }} --no-default-features
      - name: Check a package (`nightly` feature)
        if: matrix.toolchain == 'nightly'
        run: cargo check --target ${{ matrix.target }} -F nightly
      - name: Check a package (`nightly` feature without `default` feature)
        if: matrix.toolchain == 'nightly'
        run: cargo check --target ${{ matrix.target }} --no-default-features -F nightly

  test:
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os-alias:
          - ubuntu
          - macos
          - windows
        toolchain-alias:
          - msrv
          - stable
          - nightly
        include:
          - os-alias: ubuntu
            os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os-alias: macos
            os: macos-14
            target: aarch64-apple-darwin
          - os-alias: windows
            os: windows-2022
            target: x86_64-pc-windows-msvc
          - toolchain-alias: msrv
            toolchain: 1.74.0
          - toolchain-alias: stable
            toolchain: stable
          - toolchain-alias: nightly
            toolchain: nightly
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          targets: ${{ matrix.target }}
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.7.7
        with:
          key: ${{ matrix.target }}
      - name: Run tests
        run: cargo test --target ${{ matrix.target }}
      - name: Run tests (no default features)
        run: cargo test --target ${{ matrix.target }} --no-default-features
      - name: Run tests (`nightly` feature)
        if: matrix.toolchain == 'nightly'
        run: cargo test --target ${{ matrix.target }} -F nightly
      - name: Run tests (`nightly` feature without `default` feature)
        if: matrix.toolchain == 'nightly'
        run: cargo test --target ${{ matrix.target }} --no-default-features -F nightly

  rustfmt:
    name: Rustfmt
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.7.7
      - name: Check code formatted
        run: cargo fmt -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
          components: clippy
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.7.7
      - name: Check no lint warnings
        run: cargo clippy -- -D warnings
      - name: Check no lint warnings (no default features)
        run: cargo clippy --no-default-features -- -D warnings

  doc:
    name: Documentation
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.7.7
      - name: Check no `rustdoc` lint warnings
        run: RUSTDOCFLAGS="-D warnings" cargo doc --no-deps --document-private-items

  benchmark:
    name: Benchmark
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: nightly
      - name: Cache build artifacts
        uses: Swatinem/rust-cache@v2.7.7
      - name: Run benchmarks
        run: cargo bench
