# SPDX-FileCopyrightText: 2022 Shun Sakai
#
# SPDX-License-Identifier: Apache-2.0 OR MIT

name: Check Semantic Versioning

on:
  push:
    branches:
      - "release/*"
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
  workflow_dispatch:

jobs:
  semver:
    name: Check Semantic Versioning
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Check Semantic Versioning
        uses: obi1kenobi/cargo-semver-checks-action@v2.6
